"""PDF Generator — monthly current affairs PDF using reportlab (HTML fallback if not installed)."""
import os, datetime, io
from .database import Article

def _month_label(dt=None): return (dt or datetime.datetime.utcnow()).strftime("%Y-%m")
def _month_name(label):
    import calendar; y,m=label.split("-"); return f"{calendar.month_name[int(m)]} {y}"

def generate_pdf_bytes(db, month=None, exam_type="UPSC"):
    label=month or _month_label(); y,m=int(label.split("-")[0]),int(label.split("-")[1])
    start=datetime.datetime(y,m,1)
    end=datetime.datetime(y,m+1,1) if m<12 else datetime.datetime(y+1,1,1)
    articles=db.query(Article).filter(Article.include==True,Article.published_at>=start,Article.published_at<end).order_by(Article.importance_score.desc()).limit(80).all()
    if not articles:
        articles=db.query(Article).filter(Article.include==True).order_by(Article.importance_score.desc()).limit(80).all()
    try: return _with_reportlab(articles,label,exam_type)
    except ImportError: return _html_fallback(articles,label,exam_type).encode()

def _with_reportlab(articles, label, exam_type):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_CENTER
    buf=io.BytesIO()
    doc=SimpleDocTemplate(buf,pagesize=A4,leftMargin=2*cm,rightMargin=2*cm,topMargin=2*cm,bottomMargin=2*cm)
    styles=getSampleStyleSheet()
    GREEN=colors.HexColor("#24764d"); NAVY=colors.HexColor("#1a2744")
    t_style=ParagraphStyle("T",parent=styles["Title"],fontSize=24,textColor=NAVY,spaceAfter=4,alignment=TA_CENTER)
    s_style=ParagraphStyle("S",parent=styles["Normal"],fontSize=11,textColor=GREEN,spaceAfter=12,alignment=TA_CENTER)
    c_style=ParagraphStyle("C",parent=styles["Heading2"],fontSize=14,textColor=GREEN,spaceBefore=14,spaceAfter=6)
    a_title=ParagraphStyle("AT",parent=styles["Normal"],fontSize=11,fontName="Helvetica-Bold",textColor=NAVY,spaceAfter=3)
    a_body =ParagraphStyle("AB",parent=styles["Normal"],fontSize=9.5,textColor=colors.HexColor("#444"),spaceAfter=2,leading=14)
    m_style=ParagraphStyle("M",parent=styles["Normal"],fontSize=9,textColor=colors.HexColor("#316f9d"),spaceAfter=8,leading=13)
    story=[Paragraph("ExamMemory AI",t_style),Paragraph(f"Current Affairs — {_month_name(label)} | {exam_type}",s_style),HRFlowable(width="100%",color=GREEN,thickness=1.5),Spacer(1,12)]
    cats={}
    for a in articles: cats.setdefault(a.category,[]).append(a)
    for cat,arts in cats.items():
        story.append(Paragraph(f"▌ {cat}",c_style))
        for a in arts[:8]:
            block=(a.quick_json if exam_type not in("UPSC","State PSC") else a.deep_json) or a.quick_json or {}
            story.append(Paragraph(a.title,a_title))
            if block.get("why_in_news"): story.append(Paragraph(f"<b>Why in News:</b> {block['why_in_news']}",a_body))
            if block.get("key_facts"):   story.append(Paragraph(f"<b>Key Facts:</b> {' • '.join(block['key_facts'][:4])}",a_body))
            if block.get("revision_notes"): story.append(Paragraph(f"<b>Revision:</b> {block['revision_notes']}",a_body))
            if a.mcqs_json:
                mcq=a.mcqs_json[0]; story.append(Paragraph(f"<b>MCQ:</b> {mcq['question']} | <b>Ans:</b> {mcq['answer']}",m_style))
            story.append(Spacer(1,6))
    story.append(Spacer(1,20))
    story.append(Paragraph("Generated by ExamMemory AI | Read today. Revise tomorrow. Remember in the exam.",ParagraphStyle("F",parent=styles["Normal"],fontSize=8,textColor=colors.grey,alignment=TA_CENTER)))
    doc.build(story); return buf.getvalue()

def _html_fallback(articles, label, exam_type):
    cats={}
    for a in articles: cats.setdefault(a.category,[]).append(a)
    rows=""
    for cat,arts in cats.items():
        rows+=f"<h2 style='color:#24764d;border-bottom:2px solid #24764d'>{cat}</h2>"
        for a in arts[:8]:
            block=a.quick_json or {}; mcq=(a.mcqs_json or [{}])[0]
            rows+=f"""<div style='margin-bottom:16px;padding:12px;border:1px solid #ddd;border-radius:8px'>
              <strong>{a.title}</strong><br><em style='color:#647067;font-size:12px'>{a.source_name} · {a.importance_score}/10</em>
              <p>{block.get('why_in_news','')}</p><p><b>Revision:</b> {block.get('revision_notes','')}</p>
              {'<p style="color:#316f9d"><b>MCQ:</b> '+mcq.get('question','')+'<br><b>Ans:</b> '+mcq.get('answer','')+'</p>' if mcq.get('question') else ''}
            </div>"""
    return f"""<!DOCTYPE html><html><head><meta charset='UTF-8'><title>ExamMemory AI — {_month_name(label)}</title>
    <style>body{{font-family:sans-serif;max-width:900px;margin:auto;padding:32px}}</style></head><body>
    <h1 style='text-align:center;color:#1a2744'>ExamMemory AI</h1>
    <p style='text-align:center;color:#24764d'>Current Affairs — {_month_name(label)} | {exam_type}</p><hr>{rows}
    <p style='text-align:center;color:#aaa;font-size:12px'>Generated by ExamMemory AI</p></body></html>"""
